language:
  - node_js

node_js:
  - "6"
  - "7.9"
  - "8"
  - "10"

before_install:
  - npm install -g gulp-cli
  - npm install -g codecov
  - npm install -g mocha

script:
  - npm run coverage

after_success:
  - codecov
